###Insert a new music record
POST http://localhost:8080/api/v1/music
Content-Type: application/json

{
   "title": "Reincarnation of Benjamin Breeg",
   "albumId": 1,
   "duration": 240,
   "trackNumber": "1"
}

###Get all music records
GET http://localhost:8080/api/v1/music


###Get a music record by id
GET http://localhost:8080/api/v1/music/1


###Update a music record by id
PUT http://localhost:8080/api/v1/music/1
Content-Type: application/json

{
   "title": "Reincarnation of Benjamin Breeg - Remastered",
   "albumId": 1,
   "duration": 245,
   "trackNumber": "1"
}